### PR TITLE
Adding support for importing the library to build.particle.io

### PR DESCRIPTION
**Pull request by jozjan**
build.particle.io looks for spark.json instead of particle.json.

### CODE REVIEW

**Comment by kristinpeterson** [comment]
@netarc when you have a moment, can you please review?

**Comment by kristinpeterson** [comment]
@amclain can you merge and deploy? (not sure if this needs to be updated in Particle Cloud...)

**Comment by amclain** [comment]
@kristinpeterson I've merged and cut a release (2.0.2), but I don't have access on [build.particle.io](build.particle.io) to publish the new version.

**Comment by kristinpeterson** [comment]
> but I don't have access on build.particle.io to publish the new version. Is @netarc able to grant me the privilege or publish the latest version?

@netarc could you please assist @amclain ?

**Comment by netarc** [comment]
@kristinpeterson @amclain getting error 500's when trying to reimport/publish the new version, not sure if its us or something wrong with their site at the moment.

**Comment by kristinpeterson** [comment]
@netarc ok, thanks for trying! In the meantime, can you add @amclain as a contributor so that he may publish in the future as needed?  He'll be helping out w/ updates related to this library.

**Pull request merged**
